inertial_sense_node:
    ros__parameters:
        port: "/dev/ttyUSB0"
        baud: 921600
        navigation_dt_ms: 10
        stream_INS: true
        stream_IMU: false
        stream_GPS: false
        stream_GPS_info: false
        stream_baro: false
        stream_mag: false
        stream_preint_IMU: false
        stream_GPS_raw: false
        inclination: 1.14878541071
        declination: 0.20007290992
        dynamic_model: 4
        INS_rpy_radians: [1.5708, 0.0, 0.0]
        INS_xyz: [1.0, 0.0, 0.0]
        GPS_ant_xyz: [1.0, 1.0, 1.0]
        GPS_ref_lla: [40.25, -111.67, 1556.59]
        serial1_baud_rate: 115200
        NMEA_rate: 200
        NMEA_configuration: 0x0F
        NMEA_ports: 0x02
